import { type FrameGraphPostProcessTask, type IViewportLike } from "../../../../index.js";
import { NodeRenderGraphBasePostProcessBlock } from "./basePostProcessBlock.js";
/**
 * Base class for post process blocks.
 */
export declare class NodeRenderGraphBaseWithPropertiesPostProcessBlock extends NodeRenderGraphBasePostProcessBlock {
    protected _frameGraphTask: FrameGraphPostProcessTask;
    protected _useCurrentViewport: boolean;
    protected _useFullScreenViewport: boolean;
    protected _viewport: IViewportLike;
    /** If true, the depth attachment will be read-only. */
    get depthReadOnly(): boolean;
    set depthReadOnly(value: boolean);
    /** If true, the stencil attachment will be read-only. */
    get stencilReadOnly(): boolean;
    set stencilReadOnly(value: boolean);
    /** If true, color write will be disabled when applying the post process. */
    get disableColorWrite(): boolean;
    set disableColorWrite(value: boolean);
    /** If true, the post process will be generated by a back face full-screen quad (CW order). */
    get drawBackFace(): boolean;
    set drawBackFace(value: boolean);
    /** If depth testing should be enabled (default is true). */
    get depthTest(): boolean;
    set depthTest(value: boolean);
    private _setViewport;
    /** If true, the current viewport will be left unchanged. */
    get useCurrentViewport(): boolean;
    set useCurrentViewport(value: boolean);
    /** If true, a full screen viewport will be used. */
    get useFullScreenViewport(): boolean;
    set useFullScreenViewport(value: boolean);
    /** The viewport to use. */
    get viewport(): IViewportLike;
    set viewport(value: IViewportLike);
    /**
     * Gets the current class name
     * @returns the class name
     */
    getClassName(): string;
    protected _dumpPropertiesCode(): string;
    serialize(): any;
    _deserialize(serializationObject: any): void;
}
